### ISSUE TITLE
Fix `.github/workflows/codecov.yml`

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/api#377]
### Bug Report

As reported by [this GHA](https://github.com/dotkernel/api/actions/runs/12391801569):

```text
Invalid workflow file: .github/workflows/codecov.yml#L46
The workflow is not valid. .github/workflows/codecov.yml (Line: 46, Col: 11): Unexpected value 'COMPOSER_DEV_MODE=1'
```

`.github/workflows/codecov.yml` contains invalid code:

```yaml
- name: Install dependencies with composer
  env:
    COMPOSER_DEV_MODE=1
  run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
```

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z
